# Generated by Django 4.2.6 on 2023-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.CharField(max_length=30)),
                ('Item_name', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
            ],
        ),
    ]
