# Generated by Django 4.2.5 on 2023-10-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='items',
        ),
    ]
